### ISSUE TITLE
ActiveTime Top not working

### ISSUE THREAD

**Issue by yepidoodles** [SimonFlash/ActiveTime#1]
https://gyazo.com/e460b58ec4add515fdcff9241fa75e41

ActiveTime: v1.0.2
SpongeForge: 2281-5.2.0-BETA-2300

**Comment by SimonFlash** [comment]
Easily the most obscure bug I've ever had to deal with. Fixed for version 1.0.3

**Comment by yepidoodles** [comment]
It's still broken in v1.0.3 (Same SpongeForge)

https://gyazo.com/0fb4adad41da0af0af3d69bcdd2f1907

**Comment by SimonFlash** [comment]
The numbers at the end is a display issue from a change I made for better performance durring sorting. The ?# names are part of the internal system for assigning player names if they cannot be found. Users that have been online since the update shoulf now have their username stored, so please check to ensure they are getting saved.

**Comment by yepidoodles** [comment]
Yeah it seems that since updating, it's only adding the names as people log in, but shouldn't it show the time played?

**Comment by SimonFlash** [comment]
It's a result of the display change I mentioned. I'll have a patch out within the next day or two with the nect update.

**Comment by yepidoodles** [comment]
Alright
