### ISSUE TITLE
console permissions

### ISSUE THREAD

**Issue by aglarcz** [SimonFlash/ActiveTime#10]
active time check not working from console - saying i dont have permission for that - latest version on 1.10.2

**Comment by SimonFlash** [comment]
To be perfectly honest, I've forgotten about this issue three times xD

Although I was able to find the issue and fix it (release this weekend), I nearly missed the source of the problem because I didn't have the necessary logs and info about the issue. For future issues (whether here, another plugin, or just in general) include details such as console outputs, logs, messages, and the version number - 'latest' doesn't identify a specific build.

**Comment by aglarcz** [comment]
If i wrote "its saying i dont have permission for that" => then its saying just that. When i say its latest version then its latest version => even github says "latest release" or you have some other public builds? No, so stop making others look like idiots.

**Comment by aglarcz** [comment]
A bit of politeness would not be hurt, you dont have to correct everyone to your picture ;)

**Comment by SimonFlash** [comment]
I'm going to ignore the deleted message before that one.

I wasn't trying to be rude, just direct. The information I mentioned is the general basics of what an issue should have to point me in the right direction - take a look at the issue templates for Sponge as comparison.

My assumption was that you had an issue with your permissions plugin and that was sending a message, but the actual case was ActiveTime sending a message (specifically `You do not have permission to check other player's active time!`). That message would have immediately pointed to the issue.

Though under normal circumstances I can discern what latest means, the only reliable information that can uniquely identify a build is the version number. Though 1.3.1 may be latest now, this issue will remain documented long after future builds have come and gone.
