### ISSUE TITLE
[1.10.2] Time format change

### ISSUE THREAD

**Issue by Trochu** [SimonFlash/ActiveTime#12]
Hi there!

It is possible to change time format of playtime?

Now it is for example "3d14h5m30s", but if the played time format will be like "3 days 14 hours and 5 minutes" it would be really great and way more clear to read.

Thanks for reply and see ya :)

**Comment by SimonFlash** [comment]
You're not the first to say this, so I definitely think it's something to consider. I'm not entirely sure how I'd put this into the config though because there are a couple of different moving parts at play here. If I were do something like `<d> days <h> hours <m> minutes`, you might end up with things like ` 0 days 0 hours 3 minutes` - which is compounded when you factor in seconds and milliseconds. Any ideas for how this might be set up in the config?

**Comment by Trochu** [comment]
You can do it like this:

Let the default format like you have now so, for example: 
`played-time-format: "3d14h5m30s"`

but let players to define spaces and names of all time spans like this:

`played-time-format: 3 <d> 14 <h> 5 <m> 30 <s>`
`day-format: "days"`
`hour-format: "hours"`
`minute-format: "minutes"`
`second-format: "seconds"`

so player can define the displayed names for each time span (and maybe translate it into his language) and define spaces between them.

I dont know if you clearly understand what I wanted to say, but, you must, cause my english is a disaster :D

**Comment by Trochu** [comment]
2 months have passed and I want to ask you how is this little improvement going? Would you implement it in the plugin or .. ?

**Comment by SimonFlash** [comment]
It's certainly something I'd like to, but there's additional complexity to this that is missing to this. As I said in my earlier comment, applying a simple format like that will not take into account units that are absent and would result in `0 days 0 hours 3 minutes` - not exactly ideal.

For this to work, I need to identify the actual number replacement, such as `<days>`, but that also needs to be attributed to the name of the unit in order to remove units that are absent as shown above. Next, I need to ensure that spacing is correct too - if days are removed, then we want to show `"1 hour 2 minutes"` instead of `" 1 hour 2 minutes"` (note the leading space). Finally, when written out they should have the correct plurality that way we don't have something like `4 hour` or `1 minutes`.

I appreciate your patience and dedication with this though, and I'll set aside some time later tonight to puzzle over this and come up with some ideas and see where that takes us.

**Comment by SimonFlash** [comment]
The `formats` section in `activetime.core` can be used to change the formatting, which looks like:
```
formats {
    weeks="#w"
    days="#d"
    hours="#h"
    minutes="#m"
    seconds="#s"
    separator=""
}
```
* The time for the unit will replace the `#` symbol
* The `<s>` symbol can be used to insert the letter `s` if the time is not singular (with `# minute<s>`, 3 becomes `3 minutes` and 1 becomes `1 minute`)
* Units that are empty will 'cascade' down (if hours is empty, 3 hours 10 minutes becomes 190 minutes)
* Units that are not empty will be joined together with the `separator` string
