### ISSUE TITLE
Not working on API 5

### ISSUE THREAD

**Issue by SnowBlitzz** [SimonFlash/ActiveTime#9]
https://forums-cdn.spongepowered.org/uploads/default/optimized/3X/c/f/cf8afb3571f73f055a334e879844ce1351bba8a0_1_690x173.png

Same issue I reported on the sponge forums - I get this error when running any /atime command. Tested on spongeforge-1.10.2-2477-5.2.0-BETA-2731

**Comment by SimonFlash** [comment]
That picture doesn't give me any useful information about the cause of the issue. There should be a stacktrace printed to console; please include that in a gist.

Adittionally, what happens with other commands that use pagination (`/help`, `/info`, etc.)?

**Comment by SnowBlitzz** [comment]
All pagination from other plugins work fine.

Here's the stacktrace. Couldn't put it on pastebin cuz it was too big.
[fml-server-latest.log](https://github.com/SimonFlash/ActiveTime/files/1579826/fml-server-latest.log)

**Comment by SimonFlash** [comment]
To the JVM, the return value is part of a methods signature. This causes a binary breakage because the JVM attempts to extract the incorrect return type. I will look into making a PR to Sponge to update previous branches for this. In the meantime, I've added in a build for API 5 (and 6) to the latest release [here](https://github.com/SimonFlash/ActiveTime/releases/tag/v1.3.1).

Additionally, use https://gist.github.com for posting logs. It does not have a length limit and will not expire, so prefer this over pastebin.
